### ISSUE TITLE
what():  Pangolin X11: Failed to open X display

### ISSUE THREAD

**Issue by voyage19941119** [HTLife/Kintinuous-installation-guide#2]
First ,thanks for your guiding !
![195azbj0 q 8ppk7 vitjg](https://cloud.githubusercontent.com/assets/11376132/23442229/432b0264-fe62-11e6-9170-49cab292b574.png)
I built Kintinuous as directed,but it seems something going wrong with Pangolin ,
here is the screenshot during cmake pangolin,notice that: could not find Doxygen ; Oculus not found
![92ibj6_ol 1but0 ze sf d](https://cloud.githubusercontent.com/assets/11376132/23442404/281c6494-fe63-11e6-8378-a54a3fca43f6.png)

 can you help me?

**Comment by HTLife** [comment]
@voyage19941119  
I think your Pangolin installation is fine.
Are you running this with ssh remotely?
You should run Kintinuous under GUI desktop.

**Comment by voyage19941119** [comment]
@HTLife 
 yes, I'm building Kintinuous on a server shared with group members . So, I have to build it with my  own computer with GPU, not on a server ,right?

**Comment by HTLife** [comment]
@voyage19941119 Correct
And make sure your GPU has enough memory, or else it could not run in real time.

**Comment by voyage19941119** [comment]
@HTLife 
get it ,thank you very much !
Are you Chinese? I 'm a master studying in Nanjing , first year .

**Comment by HTLife** [comment]
@voyage19941119 
You're welcome.
Yup, I could speak Chinese.  (Couldn't type Chinese right now under this os)
and enjoy your SLAM research.

**Comment by shikouchen** [comment]
@HTLife hey, thanks for your answer, It happened to me when used ssh connected to google cloud to run the program(ElasticFusion).

However, what do you mean by GUI desktop, since I installed VNC for the remote server and run the program, it still didn't work, the error showed

> Xlib: extension "GLX" missing on display ":1.0".
what(): Pangolin X11: Unable to retrieve framebuffer options.

Whether is it not ok to run even under VNC?

Thanks!
